version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: q2_mysql_implementation
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: inventory
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sensor_inventory_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root123